### ISSUE TITLE
More efficient implementation

### ISSUE THREAD

**Issue by statwangz** [pizilber/IMC#1]
Dear Mr. Pini Zilber,

Congratulations on your paper being accepted by ICML!
I'm very interested in the performance of GNIMC when meets big data. Could you please give a more efficient implementation? Or could you teach me how to run your code with multiple cores?

Best regards,
Zhiwei

**Comment by pizilber** [comment]
Dear Zhiwei,

Thank you!
Adapting GNIMC to big data is indeed an interesting question. Unfortunately, currently we don't have a more efficient implementation. But since the bottleneck in GNIMC is its black-box least squares solver - I would start by tailoring a better solver for the needs of GNIMC.
As for parallel computing, this is a pretty challenging issue in Inductive Matrix Completion in general, please see Appendix D.4 in our paper (now available [here](https://proceedings.mlr.press/v162/zilber22a/zilber22a.pdf)). Hence, it is again the inner least squares problem which I would try to parallelize in order to enhance GNIMC's performance.
If you start working on a new version of GNIMC and would like to discuss your ideas, I would love to try to help.

Best,
Pini

**Comment by statwangz** [comment]
> 

Dear Pini,

Thanks for your kind reply!

Best,
Zhiwei
